# Properties的基于yml的配置
spring:
#  使用dev的配置
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


  # 监控服务器url
  boot:
    admin:
      client:
        url: http://localhost:9999

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


